### ISSUE TITLE
where are the files?

### ISSUE THREAD

**Issue by patrikx3** [jzillmann/pdf-to-markdown#1]
ciao!

how are you?

I see it parses, but i get no output. where the markdown files? 

thanks!
ciao!

![image](https://cloud.githubusercontent.com/assets/4770180/25555668/e5cd88c6-2cec-11e7-9a42-bdfb36789ccf.png)

**Comment by jzillmann** [comment]
Hey @patrikx3 there might be an javascript error causing this.
Could you open the developer console (usually Alt-Command-I) and post any javascript error you're seeing ?

Alternatively you could send me your PDF and i try by myself.
Also, which browser you are using ?

best 
Johannes

**Comment by patrikx3** [comment]
Hey!

How are you? 

![image](https://cloud.githubusercontent.com/assets/4770180/25578332/01692162-2e6e-11e7-968c-abd92b218bb4.png)

**Comment by jzillmann** [comment]
Hey @patrikx3, deployed a fix, can you retry !?

**Comment by patrikx3** [comment]
works at expected!

**Comment by jzillmann** [comment]
Awesome, happy to hear!
