### ISSUE TITLE
Grant @opengovsg MIT license for pdf2md fork

### ISSUE THREAD

**Issue by LoneRifle** [jzillmann/pdf-to-markdown#14]
Hello @jzillmann,

@opengovsg (The Open Government Products division of the Singapore Government) forked this repo a while ago, and created an npm package and CLI tool thanks to the code that you wrote.

As you are the original author of the codebase, we would like to request an MIT license for the following derivative works:

- https://github.com/opendocsg/pdf2md
- https://github.com/opendocsg/pdf2md-web
- @opengovsg equivalents of the repos above, to facilitate the transfer of those repos from @opendocsg to @opengovsg

We feel that a more permissive license than the current GPL 3.0 one would encourage more active use and maintenance of the derivative forks. For clarity, we are happy that the original repo remains on GPL 3.0, so long as @opengovsg has your permission and a license from you to publish our derivative work as MIT.

If you have any queries, do reply to this issue!

**Comment by jzillmann** [comment]
Hey @LoneRifle so i'm willing to change the the license to something like MIT or Apache 2. However i just read something along these lines that the already distributed code sticks to the license it was distributed with.
Not sure here...
I'm in the process of re-writing the library and this will come with a new license. If in the meantime there is something in can do, let me know!

**Comment by LoneRifle** [comment]
IANAL but my understanding is that as the original author of the package you have full discretion over what to license it under, including granting another license to other parties. 

Glad to hear that you are rewriting the library! We hope that you may be able to build upon the changes we have made. In light of this, we will put this on hold in favour of other priorities.

**Comment by jzillmann** [comment]
Ok, so i changed the License to MIT.

And yes you already influenced the way the i structure the rewrite. Plan is to separate the logic from the UI and make it separately usable (e.g. for a CLI). The next important point it to have a good test suite so the effects of any change are easier to judge. Also i want at some point to go through your changes to see what i can merge back. And happy to collaborate if there is any desire!
