### ISSUE TITLE
Error: Unsupported Headline Level 11

### ISSUE THREAD

**Issue by jacob14916** [jzillmann/pdf-to-markdown#21]
With the PDF file https://homepages.cwi.nl/~lex/files/dict.pdf (a ~220 pages math textbook) I get the following error in the console, and no markdown file to download:
`pdf2md.morethan.io/:1 Uncaught (in promise) Unsupported headline level: 11 (supported are 1-6)`

**Comment by jzillmann** [comment]
Hey @jacob14916 thanks for reporting this!
I deployed a quick fix and the parsing finishes now. However, i recognized the result is pretty poorly. I created #22 therefor, but that will take a while!
