### ISSUE TITLE
Gather PDF's for test suite

### ISSUE THREAD

**Issue by jzillmann** [jzillmann/pdf-to-markdown#24]
- Gather various PDF's that can used as a test suite
- Those should be safe to be added to the repository licensing wise 👀

**Comment by jzillmann** [comment]
Gathered a first set of arbitrary PDFs. I choose those kinds:
- Texts which entered `public domain`
- Texts with permissive license like `Creative Common BY 4.0`

There are some sites indexing public domain works (gutenberg, https://sffaudio.herokuapp.com/pdf/mobile)
and with Google it's possible to restrict search to license (in advanced search).

Also i'm assuming PDF's from projects like https://github.com/asciidoctor/asciidoctor-pdf/tree/main/examples are fine to use as well.

**Comment by steveisakson** [comment]
https://www.ecfr.gov/current/title-14/chapter-I/subchapter-G/part-139

--> use the Print/PDF button in the left sidebar.

![image](https://github.com/user-attachments/assets/1a7c5581-56ed-4bb0-ab29-60279719a716)
