### ISSUE TITLE
Fix: No valid versions available for pdf-to-markdown

### ISSUE THREAD

**Issue by LucaHermann** [jzillmann/pdf-to-markdown#35]
[![Image from Gyazo](https://i.gyazo.com/8113d17161bf038bd2e496bf9f5f277d.png)](https://gyazo.com/8113d17161bf038bd2e496bf9f5f277d)

You should consider change the URL of your online website https://pdf2md.morethan.io/ because pdf2md is an other package npm [pdf2md](https://www.npmjs.com/package/@opendocsg/pdf2md).

**Comment by jzillmann** [comment]
pdf-to-markdown isn't on `npm` (yet).
`pdf2md` is a fork of `pdf-to-markdown` enabling terminal usage.
