### ISSUE TITLE
Parsing Metadata doesn't finish

### ISSUE THREAD

**Issue by Sammeeey** [jzillmann/pdf-to-markdown#47]
After uploading my markdown file the page doesn't stop to display the following screen.
![image](https://user-images.githubusercontent.com/49591562/179531200-a3ec0c25-b76f-49f1-8722-f6148a0ca13a.png)

Nothing to download here for me - nor any progress.

**Comment by darkcheftar** [comment]
Is it possible for you to share the pdf?
So that I can try replicating the scenario.

**Comment by Sammeeey** [comment]
Now it actually works without any problems.
I don't know if I previously used a different PDF.
