### ISSUE TITLE
UTF-8 Support

### ISSUE THREAD

**Issue by sati-bodhi** [jzillmann/pdf-to-markdown#5]
Is it possible to add utf-8 support to the app? Trying to convert pdfs with CJK characters ended up with garbled text.

**Comment by jzillmann** [comment]
Hey @sati-bodhi , the site is using https://mozilla.github.io/pdf.js/ for the underlying parsing.
Can you check if your PDF renders correctly with it ? You should be able to test through https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by jzillmann** [comment]
Hmm, i'm confused a bit.. You cloned pdf.js or pdf-markdown ?
As a first step i would recommend to just upload your PDF to https://mozilla.github.io/pdf.js/web/viewer.html. If this online viewer displays your PDF correctly, we know that pdf.js ia able to parse your PDF and we can go a step further, if not, we probably reached a dead end...

**Comment by sati-bodhi** [comment]
I cloned pdf.js
I did the upload and it showed correctly. 
![default](https://user-images.githubusercontent.com/7592695/38770140-9042fbd0-4040-11e8-8e8a-53965d586aed.png)

**Comment by sati-bodhi** [comment]
The http://pdf2md.morethan.io/ engine works for this sample: 

[sample_success.pdf](https://github.com/jzillmann/pdf-to-markdown/files/1940855/sample_success.pdf)
![default](https://user-images.githubusercontent.com/7592695/39166159-d13dbe5a-47ba-11e8-9f95-b6c4aab298e8.png)

But not this one: 

[sample_fail.pdf](https://github.com/jzillmann/pdf-to-markdown/files/1940859/sample_fail.pdf)
![default](https://user-images.githubusercontent.com/7592695/39166197-0e2583de-47bb-11e8-8157-b390df22f424.png)

Both can be rendered correctly by the online viewer: 

![default](https://user-images.githubusercontent.com/7592695/39166284-7033a2c2-47bb-11e8-99b3-1e5587767b2c.png)

![default](https://user-images.githubusercontent.com/7592695/39166266-57a617e4-47bb-11e8-9347-f534b52ff04f.png)

**Comment by jzillmann** [comment]
Hey @sati-bodhi thanks for the samples. I tried a few things but had no luck so far...
Asked the pdf.js community for help: https://github.com/mozilla/pdf.js/issues/9692

**Comment by jzillmann** [comment]
Based on the response in https://github.com/mozilla/pdf.js/issues/9692 i'm closing this as won't fix.
The PDF seems to have a incomplete ToUnicode data...
